ASE , OBRA SOCIAL ACCION SOCIAL DE EMPRESARIOS                                                                                                                                                         
OSAPYEA , OBRA SOCIAL ACEROS PARANA                                                                                                                                                                        
APDIS , OBRA SOCIAL ASOCIACION DEL PERSONAL DE DIRECCION DE LA INDUSTRIA SIDERURGICA                                                                                                                     
APSOT , OBRA SOCIAL ASOCIACION DEL PERSONAL SUPERIOR DE LA ORGANIZACION TECHINT                                                                                                                          
OSBA , OBRA SOCIAL BANCARIA ARGENTINA                                                                                                                                                                   
OSEIV , OBRA SOCIAL DE  EMPLEADOS DE LA INDUSTRIA DEL VIDRIO                                                                                                                                             
OSADEF , OBRA SOCIAL DE  LAS ASOCIACIONES DE EMPLEADOS DE FARMACIA                                                                                                                                        
OSAC , OBRA SOCIAL DE ACTORES                                                                                                                                                                           
OSA , OBRA SOCIAL DE AERONAVEGANTES                                                                                                                                                                    OSALARA , OBRA SOCIAL DE AGENTES DE LOTERIAS Y AFINES DE LA REPUBLICA  ARGENTINA                                                                                                                           
OSAPM , OBRA SOCIAL DE AGENTES DE PROPAGANDA MEDICA DE LA REPUBLICA ARGENTINA                                                                                                                            
OSADRA , OBRA SOCIAL DE ARBITROS DEPORTIVOS DE LA REPUBLICA ARGENTINA                                                                                                                                     
OSCEP , OBRA SOCIAL DE CAPATACES  ESTIBADORES PORTUARIOS                                                                                                                                                 
OSCOMM , OBRA SOCIAL DE CAPITANES DE ULTRAMAR Y OFICIALES DE LA MARINA MERCANTE                                                                                                                           
OSCE , OBRA SOCIAL DE CERAMISTAS                                                                                                                                                                        
OSCHOCA , OBRA SOCIAL DE CHOFERES DE CAMIONES                                                                                                                                                              OSCAMGLYP , OBRA SOCIAL DE COLOCADORES DE AZULEJOS, MOSAICOS, GRANITEROS, LUSTRADORES Y PORCELANEROS                                                                                                         
OSCN , OBRA SOCIAL DE COMISARIOS NAVALES                                                                                                                                                                OSCCPTAC , OBRA SOCIAL DE CONDUCTORES CAMIONEROS Y PERSONAL DEL TRANSPORTE AUTOMOTOR DE CARGAS                                                                                                              
OSCRAIA , OBRA SOCIAL DE CONDUCTORES DE REMISES Y AUTOS AL INSTANTE Y AFINES                                                                                                                               
CTCP , OBRA SOCIAL DE CONDUCTORES DE TRANSPORTE COLECTIVO DE PASAJEROS                                                                                                                                  OSCONARA , OBRA SOCIAL DE CONDUCTORES NAVALES                                                                                                                                                               
OSDO , OBRA SOCIAL DE DIRECCION OSDO                                                                                                                                                                    
WITCEL , OBRA SOCIAL DE DIRECCIÓN WITCEL                                                                                                                                                                  
OSDOP , OBRA SOCIAL DE DOCENTES PARTICULARES                                                                                                                                                             
OSEDA , OBRA SOCIAL DE EMPLEADOS DE DESPACHANTES DE ADUANA                                                                                                                                               
OSEMM , OBRA SOCIAL DE EMPLEADOS DE LA MARINA MERCANTE                                                                                                                                                   
OSETRA , OBRA SOCIAL DE EMPLEADOS DEL TABACO DE LA REPUBLICA ARGENTINA                                                                                                                                    
OSETYA , OBRA SOCIAL DE EMPLEADOS TEXTILES Y AFINES                                                                                                                                                       
OSEAM , OBRA SOCIAL DE ENCARGADOS APUNTADORES MARITIMOS                                                                                                                                                  
OSFOT , OBRA SOCIAL DE FOTOGRAFOS                                                                                                                                                                        
OSGMGM , OBRA SOCIAL DE GUINCHEROS Y MAQUINISTAS DE GRUAS MOVILES                                                                                                                                         
OSJPVYF , OBRA SOCIAL DE JARDINEROS, PARQUISTAS, VIVERISTAS Y FLORICULTORES DE LA REPUBLICA ARGENTINA                                                                                                      
OSJOMN , OBRA SOCIAL DE JEFES Y OFICIALES MAQUINISTAS NAVALES                                                                                                                                             
OSSEG , OBRA SOCIAL DE LA ACTIVIDAD DE SEGUROS, REASEGUROS, CAPITALIZACION Y AHORRO Y PRESTAMO PARA LA VIVIENDA                                                                                          
OSAM , OBRA SOCIAL DE LA ACTIVIDAD MINERA                                                                                                                                                               
OSFATUN , OBRA SOCIAL DE LA FEDERACION ARGENTINA DEL TRABAJADOR  DE LAS UNIVERSIDADES NACIONALES                                                                                                          FEDECAMARAS , OBRA SOCIAL DE LA FEDERACION DE CAMARAS Y CENTROS COMERCIALES ZONALES DE LA REPUBLICA ARGENTINA (FEDECAMARAS)                                                                                    OSFGPICD , OBRA SOCIAL DE LA FEDERACION GREMIAL DE LA INDUSTRIA DE LA CARNE Y SUS DERIVADOS                                                                                                                 
OSIPA , OBRA SOCIAL DE LA INDUSTRIA DE PASTAS ALIMENTICIAS                                                                                                                                               
OSUOMRA , OBRA SOCIAL DE LA UNION OBRERA METALURGICA DE LA REPUBLICA ARGENTINA                                                                                                                             
OSDEL , OBRA SOCIAL DE LOCUTORES                                                                                                                                                                         
OSSIMRA , OBRA SOCIAL DE LOS  SUPERVISORES DE LA INDUSTRIA METALMECANICA DE LA REPUBLICA ARGENTINA                                                                                                         
OSUCI , OBRA SOCIAL DE LOS CORTADORES DE LA INDUMENTARIA    
OSECAC , OBRA SOCIAL DE LOS EMPLEADOS DE COMERCIO Y ACTIVIDADES CIVILES                                                                                                                                   
OSPUAYE , OBRA SOCIAL DE LOS PROFESIONALES UNIVERSITARIOS DEL AGUA Y LA ENERGIA ELECTRICA                                                                                                                  
OSTEE , OBRA SOCIAL DE LOS TRABAJADORES DE LAS EMPRESAS DE ELECTRICIDAD                                                                                                                                  
OSMTT , OBRA SOCIAL DE MAQUINISTAS DE TEATRO Y TELEVISION                                                                                                                                                
OSDEM , OBRA SOCIAL DE MUSICOS                                                                                                                                                                           OSOEFRNN , OBRA SOCIAL DE OBREROS EMPACADORES DE FRUTA  DE RIO NEGRO Y NEUQUEN                                                                                                                             OSOETSYLARA , OBRA SOCIAL DE OBREROS Y EMPLEADOS TINTOREROS SOMBREREROS Y LAVADEROS DE LA REPUBLICA ARGENTINA
OSPCRP , OBRA SOCIAL DE PATRONES DE CABOTAJE DE RIOS Y PUERTOS                                                                                                                                            
OSPETAX , OBRA SOCIAL DE PEONES DE TAXIS DE LA CAPITAL FEDERAL                                                                                                                                             
OSPET , OBRA SOCIAL DE PETROLEROS                                                                                                                                                                        
OSPAR , OBRA SOCIAL DE PORTUARIOS ARGENTINOS                                                                                                                                                             
OSRJA , OBRA SOCIAL DE RELOJEROS Y JOYEROS                                                                                                                                                               
OSSB , OBRA SOCIAL DE SERENOS DE BUQUES                                                                                                                                                                 
OSTECF , OBRA SOCIAL DE TECNICOS DE FUTBOL                                                                                                                                                                
OSTVLA , OBRA SOCIAL DE TECNICOS DE VUELO DE LINEAS AEREAS                                                                                                                                                
OSTIG , OBRA SOCIAL DE TRABAJADORES DE LA INDUSTRIA DEL GAS                                                                                                                                              
OSTRAC , OBRA SOCIAL DE TRABAJADORES DE LAS COMUNICACIONES                                                                                                                                                
OSTPBA , OBRA SOCIAL DE TRABAJADORES DE PRENSA DE BUENOS AIRES                                                                                                                                            
OSV , OBRA SOCIAL DE VAREADORES                                                                                                                                                                        
OSVARA , OBRA SOCIAL DE VENDEDORES AMBULANTES DE LA REPUBLICA ARGENTINA                                                                                                                                   
OSVVRA , OBRA SOCIAL DE VIAJANTES VENDEDORES DE LA REPUBLICA ARGENTINA. (ANDAR)                                                                                                                           
OSYC , OBRA SOCIAL DE YACIMIENTOS CARBONIFEROS                                                                                                                                                          
OSPATCA , OBRA SOCIAL DEL PERSONAL ADMINISTRATIVO Y TECNICO DE LA CONSTRUCCION Y AFINES                                                                                                                    
OSPA , OBRA SOCIAL DEL PERSONAL AERONAUTICO                                                                                                                                                             
OSPACP , OBRA SOCIAL DEL PERSONAL AUXILIAR DE CASAS PARTICULARES                                                                                                                                          
OSPADEP , OBRA SOCIAL DEL PERSONAL DE AERONAVEGACION DE ENTES PRIVADOS                                                                                                                                     
OSPAGA , OBRA SOCIAL DEL PERSONAL DE AGUAS GASEOSAS Y AFINES                                                                                                                                              
OSPBLCA , OBRA SOCIAL DEL PERSONAL DE BARRACAS DE LANAS, CUEROS Y ANEXOS                                                                                                                                   
OSPCYD , OBRA SOCIAL DEL PERSONAL DE CARGA Y DESCARGA                                                                                                                                                     
OSIM , OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LA INDUSTRIA METALURGICA  Y DEMAS ACTIVIDADES EMPRESARIAS                                                                                               
OSDIPP , OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LA INDUSTRIA PRIVADA DEL PETROLEO                                                                                                                      OSLPASTEUR , OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LA SANIDAD LUIS PASTEUR                                                                                                                                 
OPDEA , OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LAS EMPRESAS DE LA ALIMENTACION Y DEMAS ACTIVIDADES EMPRESARIAS                                                                                         
FRUTOS , OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LAS EMPRESAS QUE ACTUAN EN FRUTOS DEL PAIS                                                                                                              
WHOPE , OBRA SOCIAL DEL PERSONAL DE DIRECCION DE PERFUMERIA E.W. HOPE                                                                                                                                    OSPERYHRA , OBRA SOCIAL DEL PERSONAL DE EDIFICIOS DE RENTA Y HORIZONTAL DE LA REPUBLICA ARGENTINA                                                                                                           OSPEFYEPCA , OBRA SOCIAL DEL PERSONAL DE EMPRESAS FIAT Y EMPRESAS PEUGEOT CITROEN ARGENTINA                                                                                                                   
OSPEDYC , OBRA SOCIAL DEL PERSONAL DE ENTIDADES DEPORTIVAS Y CIVILES                                                                                                                                       
OSPE , OBRA SOCIAL DEL PERSONAL DE ESCRIBANOS                                                                                                                                                           OSPESGYPE , OBRA SOCIAL DEL PERSONAL DE ESTACIONES DE SERVICIO, GARAGES, PLAYAS DE ESTACIONAMIENTO Y LAVADEROS AUTOMATICOS
UPFPARA , OBRA SOCIAL DEL PERSONAL DE FABRICAS DE PINTURA                                                                                                                                                  
OSPF , OBRA SOCIAL DEL PERSONAL DE FARMACIA                                                                                                                                                             
OSPIDA , OBRA SOCIAL DEL PERSONAL DE IMPRENTA, DIARIOS Y AFINES                                                                                                                                           
OSPIQYP , OBRA SOCIAL DEL PERSONAL DE INDUSTRIAS QUIMICAS Y PETROQUIMICAS                                                                                                                                  
OSPIS , OBRA SOCIAL DEL PERSONAL DE INSTALACIONES SANITARIAS
OSPEJ , OBRA SOCIAL DEL PERSONAL DE JABONEROS                                                                                                                                                            
OSPACA , OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD CERVECERA Y AFINES                                                                                                                                      
OSPAT , OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD DEL TURF                                                                                                                                                
OSPAP , OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD PERFUMISTA                                                                                                                                              
OSPAV , OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD VITIVINICOLA                                                                                                                                            
OSPECON , OBRA SOCIAL DEL PERSONAL DE LA CONSTRUCCION                                                                                                                                                      
OSPEC , OBRA SOCIAL DEL PERSONAL DE LA EMPRESA NACIONAL DE CORREOS Y TELEGRAFOS S.A. Y DE LAS  COMUNICACIONES DE LA REPULICA ARGENTINA
OSPEP , OBRA SOCIAL DEL PERSONAL DE LA ENSEÑANZA PRIVADA                                                                                                                                                 
OSPIA , OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DE LA ALIMENTACION                                                                                                                                      
OSPICAL , OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CALZADO                                                                                                                                             
OSPIC , OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CAUCHO                                                                                                                                              
OSPICHA , OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CHACINADO Y AFINES                                                                                                                                  
OSPICA , OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CUERO Y AFINES                                                                                                                                      
OSPIHMP , OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL HIELO Y MERCADOS PARTICULARES                                                                                                                       
OSPIP , OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL PLASTICO                                                                                                                                            
OSPIV , OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL VESTIDO                                                                                                                                             
OSPIVE , OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL VIDRIO                                                                                                                                              
OSPILM , OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA LADRILLERA A MAQUINA                                                                                                                                    
OSPIL , OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA LECHERA                                                                                                                                                 
OSPIM , OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA MADERERA                                                                                                                                                
OSPIMO , OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA MOLINERA                                                                                                                                                
OSPIT , OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA TEXTIL                                                                                                                                                  
OSPP , OBRA SOCIAL DEL PERSONAL DE LA PUBLICIDAD                                                                                                                                                        
OSPSA , OBRA SOCIAL DEL PERSONAL DE LA SANIDAD ARGENTINA                                                                                                                                                 
OSTEL , OBRA SOCIAL DEL PERSONAL DE LAS TELECOMUNICACIONES DE LA REPUBLICA ARGENTINA                                                                                                                     
OSLYF , OBRA SOCIAL DEL PERSONAL DE LUZ Y FUERZA DE CORDOBA                                                                                                                                              
OSPM , OBRA SOCIAL DEL PERSONAL DE MAESTRANZA                                                                                                                                                           
OSPEPA , OBRA SOCIAL DEL PERSONAL DE PANADERIAS                                                                                                                                                           
OSPPEA , OBRA SOCIAL DEL PERSONAL DE PELUQUERIAS, ESTETICAS Y AFINES                                                                                                                                      
OSPPRA , OBRA SOCIAL DEL PERSONAL DE PRENSA DE LA REPUBLICA ARGENTINA                                                                                                                                     
OSPSIP , OBRA SOCIAL DEL PERSONAL DE SEGURIDAD COMERCIAL, INDUSTRIAL E INVESTIGACIONES PRIVADAS                                                                                                           
OSPESA , OBRA SOCIAL DEL PERSONAL DE SOCIEDADES DE AUTORES Y AFINES                                                                                                                                       
OSPTV , OBRA SOCIAL DEL PERSONAL DE TELEVISION                                                                                                                                                           
OSPACLA , OBRA SOCIAL DEL PERSONAL DEL AUTOMOVIL  CLUB ARGENTINO                                                                                                                                           
OSPECA , OBRA SOCIAL DEL PERSONAL DEL CAUCHO                                                                                                                                                              
OSPEPU , OBRA SOCIAL DEL PERSONAL DEL ESPECTACULO PUBLICO                                                                                                                                                 
OSPOCE , OBRA SOCIAL DEL PERSONAL DEL ORGANISMO DE CONTROL EXTERNO                                                                                                                                        
OSPPCYQ , OBRA SOCIAL DEL PERSONAL DEL PAPEL, CARTON Y QUIMICOS                                                                                                                                            OSUTHGRA , OBRA SOCIAL DEL PERSONAL DEL TURISMO, HOTELERO Y GASTRONOMICO DE LA UNION  DE TRABAJADORES  DEL TURISMO HOTELEROS Y GASTRONOMICOS DE LA REPUBLICA  ARGENTINA
OSDIC , OBRA SOCIAL DEL PERSONAL DIRECTIVO DE LA INDUSTRIA DE LA CONSTRUCCION                                                                                                                            
OSPG , OBRA SOCIAL DEL PERSONAL GRAFICO                                                                                                                                                                 
OSJERA , OBRA SOCIAL DEL PERSONAL JERARQUICO DE LA REPUBLICA ARGENTINA PARA EL PERSONAL JERARQUICO DE LA INDUSTRIA GRAFICA Y EL PERSONAL JERARQUICO DEL AGUA Y LA ENERGIA
OSPMA , OBRA SOCIAL DEL PERSONAL MARITIMO                                                                                                                                                               OSPMJCHPSI , OBRA SOCIAL DEL PERSONAL MENSUALIZADO DEL JOCKEY CLUB DE BUENOS AIRES Y LOS HIPODROMOS DE PALERMO Y SAN ISIDRO                                                                                   
OSPRERA , OBRA SOCIAL DEL PERSONAL RURAL Y ESTIBADORES DE LA REPUBLICA ARGENTINA
OSSHELL , OBRA SOCIAL DEL PERSONAL SHELL-CAPSA                                                                                                                                                             
OSPEA , OBRA SOCIAL DEL PERSONAL SUPERIOR Y PROFESIONAL DE EMPRESAS AEROCOMERCIALES                                                                                                                      
OSPTA , OBRA SOCIAL DEL PERSONAL TECNICO AERONAUTICO                                                                                                                                                     
OSPEGAP , OBRA SOCIAL DEL PETROLEO Y GAS PRIVADO                                                                                                                                                           
OSMATA , OBRA SOCIAL DEL SINDICATO DE MECANICOS Y AFINES DEL TRANSPORTE AUTOMOTOR                                                                                                                         
OSFE , OBRA SOCIAL FERROVIARIA                                                                                                                                                                          
OSMA , OBRA SOCIAL MODELOS ARGENTINOS                                                                                                                                                                   
MITA , OBRA SOCIAL MUTUALIDAD INDUSTRIAL TEXTIL ARGENTINA                                                                                                                                               
OSPELMM , OBRA SOCIAL PARA EL  PERSONAL DE EMPRESAS DE  LIMPIEZA, SERVICIOS Y MAESTRANZA DE MENDOZA                                                                                                        
OSEDEIV , OBRA SOCIAL PARA EL PERSONAL DE DIRECCION DE LA INDUSTRIA VITIVINICOLA Y AFINES                                                                                                                  
OSIAD , OBRA SOCIAL PARA EL PERSONAL DE LA INDUSTRIA ACEITERA, DESMOTADORA Y AFINES
OSOSS , OBRA SOCIAL PARA EL PERSONAL DE OBRAS Y SERVICIOS SANITARIOS
OSPLAD , OBRA SOCIAL PARA LA ACTIVIDAD DOCENTE
OSTEP , OBRA SOCIAL PARA LOS TRABAJADORES DE LA EDUCACION PRIVADA
OSPLA , OBRA SOCIAL PARA PILOTOS DE LINEAS AEREAS COMERCIALES Y REGULARES
OSPCN , OBRA SOCIAL UNION PERSONAL DE LA UNION DEL  PERSONAL CIVIL DE LA NACION
OSYPF , OBRA SOCIAL YPF
OSDE , OSDE ORGANIZACION DE SERVICIOS DIRECTOS EMPRESARIOS